name: WeeSmartVN CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the site
      run: |
        ls -la
        pwd
        rm -rf /var/www/wee/*
        cp -R $(pwd)/* /var/www/wee
        echo visit: https://weesmartvn.com
